export const GET_USER_DATA = "GET_USER_DATA";
export const GET_USER_DATA_SUCCESS = "GET_USER_DATA_SUCCESS";
export const NAVIGATE_HOME = "NAVIGATE_HOME";
export const NAVIGATE_REDUX = "NAVIGATE_REDUX"
export const NAVIGATE_FIREBASE = "NAVIGATE_FIREBASE"
export const GET_USER_FROM_FIREBASE = "GET_USER_FROM_FIREBASE"